#include "IntegralType.hpp"
#include "IsAoS.hpp"
#include "IsComplex.hpp"
#include "IsInplace.hpp"
#include "IsStrided.hpp"
#include "MemoryType.hpp"
#include "NumDims.hpp"
#include "RemoveModifiers.hpp"
